-- AlterTable
ALTER TABLE "brand" ALTER COLUMN "name" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1024);

-- AlterTable
ALTER TABLE "category" ALTER COLUMN "name" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1024);

-- AlterTable
ALTER TABLE "gender" ALTER COLUMN "name" SET DATA TYPE VARCHAR(40);

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "name" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1024);

-- AlterTable
ALTER TABLE "sub_category" ALTER COLUMN "name" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1024);

-- AlterTable
ALTER TABLE "sub_category_type" ALTER COLUMN "name" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1024);
